version: "3.8"
services:
  back-end:
    build: ./back-end
    container_name: back-end
    ports:
      - '4000:4000'
    volumes:
      - './back-end:/app'
      - '/app/node_modules'

  front-end:
    build: ./front-end
    container_name: front-end
    ports:
      - '8080:8080'
    volumes:
      - './front-end:/app'
      - '/app/node_modules'
    stdin_open: true