version: "3.8"
services:
  db:
    container_name: postgres
    restart: always
    image: postgres
    ports:
      - '5432:5432'
    volumes:
      - 'data:/var/lib/postgresql'
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db_name

  front-end:
    build: ./front-end
    container_name: front-end
    ports:
      - '3000:3000'
    volumes:
      - './front-end:/app'
      - '/app/node_modules'
    stdin_open: true
  back-end:
    build: ./back-end
    restart: always
    container_name: back-end
    ports:
      - '4000:4000'
    depends_on:
      - db
    volumes:
      - './back-end:/app'
      - '/app/node_modules'
      - 'data:/app/data'

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080
volumes:
  data: {}