version: "3.8"
services:
  back-end:
    build: ./back-end
    container_name: back-end
    ports:
      - '4000:4000'
    depends_on:
      - db
    volumes:
      - './back-end:/app'
      - '/app/node_modules'

  front-end:
    build: ./front-end
    container_name: front-end
    ports:
      - '3000:3000'
    volumes:
      - './front-end:/app'
      - '/app/node_modules'
    stdin_open: true
  db:
    container_name: postgres
    restart: always
    image: postgres
    ports:
      - '5433:${DB_PORT}'
    volumes:
      - 'data:/var/lib/postgresql'
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

  adminer:
    image: adminer
    restart: always
    depends_on:
      - back-end
    ports:
      - 8080:8080
volumes:
  data: {}